apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo
data:
  RAILS_ENV: "production"
  RAILS_LOG_TO_STDOUT: "true"
  DATABASE_HOST: 10.1.0.3
  DATABASE_USER: "post_manage"
  DATABASE_NAME: "post_manage"
  RAILS_MASTER_KEY: 786289718154217167f2b017a6f82bbd